### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by iMattPro** [phpbb-extensions/collapsible-categories#12]
Outstanding to do items:
- [x] Program the four methods in the operator class (PR #15 )
- [x] Program the event listener, which needs to define some template vars we created and are using, also see code ideas for reference: https://gist.github.com/VSEphpbb/0b16e370cccfe3ed76ed (PR #16 )
- [x] Add a language system so mouse over the clickable buttons reveals a tooltip, ie: "Click to show/hide forums"

**Comment by rxu** [comment]
I'm going to take `class operator` for now if nobody minds (posting it just to avoid jobs collisions).

**Comment by Wolfsblvt** [comment]
Language system will be added with PR #21.
