### ISSUE TITLE
How to deal with styles that already have collapsible categories?

### ISSUE THREAD

**Issue by iMattPro** [phpbb-extensions/collapsible-categories#31]
A bunch of 3rd party styles already have cookie based collapsible categories built in.

digi, elegance, pbtech, pbwow, simplicity, and more.

Should we:
- Hide our collapsible cat in their style?
- Hide theirs, and make ours look like theirs in their style?

The first option is easiest to do. But the advantage of the second would be the collapsed prefs of the user would be maintained when switching between styles.

**Comment by Wolfsblvt** [comment]
I am all for 2).
Should be a bit work for each, but it is possible, and it would be an improvement for both, the custom style and our extension (button style).

**Comment by iMattPro** [comment]
2 is pretty easy. I've actually done some styles already and it works good.

**Comment by iMattPro** [comment]
We should treat styles like languages. People can make their own styles and post them to a support topic, and we can eventually add them to the official package.

**Comment by iMattPro** [comment]
All it takes to work with other styles is usually just tweaking the color codes. Sometimes it may be needed to adjust the margins for positioning, or border radius. To replace a style's existing buttons, just add some css to hide their button and tweak our button colors, borders, and maybe size values to match.

**Comment by iMattPro** [comment]
We should probably also clear any cookies made by these styles to our migrations too, to prevent conflicts.

**Comment by Wolfsblvt** [comment]
That would be cool. It is also cleaner to remove unused cookies.

**Comment by iMattPro** [comment]
oops, we can't do that. cookies are user based. so users having issues would just have to delete all board cookies.
