### ISSUE TITLE
New Template Event(s)

### ISSUE THREAD

**Issue by iMattPro** [phpbb-extensions/collapsible-categories#6]
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/styles/prosilver/template/forumlist_body.html#L21
After that line we could request a new template event which we can use to install our clickable button. This button could also contain all the needed data so we could reduce our JS DOM injections.

We should look at this once we have this ext somewhat functional.

**Comment by iMattPro** [comment]
PR for new event in the core: https://github.com/phpbb/phpbb/pull/3530

We would use the append event

**Comment by iMattPro** [comment]
We should also check for BOTS in the template event that will add the button, and not display the buttons if it is a bot.

**Comment by Wolfsblvt** [comment]
Yeah, just a small `<!-- IF not S_IS_BOT -->` needed. Good idea.
