### ISSUE TITLE
Absolution styles files are empty = not working

### ISSUE THREAD

**Issue by raykai** [phpbb-extensions/collapsible-categories#64]
your styles Absolution files have no code and is missing folders and files. thus its not working for that theme.

collapsiblecategories > styles > Absolution > template >event

there are 3 files there:
forumlist_body_category_header_before.html
forumlist_body_category_header_row_append.html
overall_header_head_append.html

all of them have no code in it. (O_o)

its also missing the theme folder and css files and the Js folder and files

hope to see a fix soon.

**Comment by raykai** [comment]
i have an old backup that had the codes and files for it. you might need to look if all the code you did is update tho here is a zip file of it
[Absolution.zip](https://github.com/phpbb-extensions/collapsible-categories/files/1220008/Absolution.zip)

**Comment by iMattPro** [comment]
Absolution for 3.1 had collapsers, which the author removed for 3.2 for no apparent reason. Ask the author to put back the feature his style already had in 3.1. Becaue his style had them in 3.1 and then not in 3.2 means this extension can not support that style.

**Comment by raykai** [comment]
well if you add the files i added in my last post it does work. the author is not answering and is not on phpbb no more i tried contacting him many times.

**Comment by iMattPro** [comment]
No that breaks it for 3.1 users. The problem is the style.

**Comment by raykai** [comment]
here i posted on the themes phpbb page:
 [https://www.phpbb.com/customise/db/style/absolution/support/topic/181476?p=581371#p581371](https://www.phpbb.com/customise/db/style/absolution/support/topic/181476?p=581371#p581371)

hope the theme author can fix it. Seeing its the 3rd most downloaded theme on phpbb.
