### ISSUE TITLE
Add support for flat-style

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/collapsible-categories#78]
https://www.phpbb.com/customise/db/style/flat_style/

**Comment by VSEphpbb** [comment]
Well it was working with that style... Then the author went and broke it.

**Comment by iMattPro** [comment]
You should ask that style's author to fix it. The problem is in their style, so they have to fix it (they put in their CSS rules that override this extension's button, so they need to fix what they've done to collapsible categories).

**Comment by 3D-I** [comment]
Yeah. I will fix it myself I guess. ;-) Thx.

**Comment by iMattPro** [comment]
Delete everything they've done under `/* Collapsible categories */` in their CSS and just have
```css
a.collapse-btn { margin: 23px 5px 0; }
```
Unfortunately we can't fix this because they've used `!important` which means their hacks will always win out...so they will need to fix and re-release.

**Comment by 3D-I** [comment]
Well, last update for the style I did it myself for our site (can't wait) so I'll deal with this,

Ofcourse I will PM the author and let him know what a do in order to amend their styles.

Much appreciated. :smile_cat:

**Comment by eeji** [comment]
Fixed. Until a new version is validated please use the attached zip to replace styles/flat-style/theme/flat.css and [styles/flat-style-XXX/theme/colour-override.css[/c] in Flat Style colour variants, where XXX is the colour (all colours are included in the zip)
[flat-style_collapsible_cat_fix.zip](https://github.com/phpbb-extensions/collapsible-categories/files/3683081/flat-style_collapsible_cat_fix.zip)

Also posted fix to phpBB.com https://www.phpbb.com/customise/db/style/flat_style/support/topic/208506?p=708641#p708641

**Comment by 3D-I** [comment]
Ah, very well thx @eeji
